summary:
	pandoc summary-report-20260307.md -o summary-report-20260307.pdf -V geometry:margin=1in --variable fontsize=10pt --variable mainfont=Verdana --pdf-engine=xelatex -f markdown-implicit_figures -s
